#!/bin/sh
#
# This script generates a bunch of memusexx binaries.  In MINIX, memory
# allocation is static, so we need to have a lot of different sizes to
# experiment with memory holes.
#
# To run the script, simply type mkmemuse
#
# forkmem is used to fork off a bunch of the memuse processes.
#

for SZ in 1 3 6 8 12 16 24 32 40;
  do
    cc -o memuse$SZ -DSIZEINMB=$SZ usemem.c;
  done;

cc -O3 -o forkmem forkmem.c;
